name: "OpenTelemetry Distribution Builder"
description: "Build custom OpenTelemetry Distributions"

inputs:
  manifest:
    description: "Path to the collector manifest file"
    required: true
    default: "./manifest.yaml"
  artifact_dir:
    description: "Directory to store build artifacts"
    required: true
    default: "/github/workspace/artifacts"
  os:
    description: "Target operating systems (comma-separated: linux,darwin,windows)"
    required: false
    default: "linux"
  arch:
    description: "Target architectures (comma-separated: amd64,arm64)"
    required: false
    default: "amd64"
  ocb_version:
    description: "Version of OpenTelemetry Collector Builder to use"
    required: false
  supervisor_version:
    description: "Version of OpenTelemetry Collector Supervisor to use"
    required: false
  go_version:
    description: "Version of Go to use for building"
    required: false

runs:
  using: "docker"
  image: "builder/Dockerfile"
  env:
    INPUT_MANIFEST: ${{ inputs.manifest }}
    INPUT_OS: ${{ inputs.os }}
    INPUT_ARCH: ${{ inputs.arch }}
    INPUT_OCB_VERSION: ${{ inputs.ocb_version }}
    INPUT_ARTIFACT_DIR: ${{ inputs.artifact_dir }}
    INPUT_SUPERVISOR_VERSION: ${{ inputs.supervisor_version }}
    INPUT_GO_VERSION: ${{ inputs.go_version }}

branding:
  icon: "package"
  color: "blue"
