name: OpenTelemetry Distribution Build

on:
  push:
    paths:
      - "collector/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Package
        uses: observiq/otel-distro-builder@v1
        with:
          manifest: collector/manifest.yaml
          output-dir: ./dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collector-packages
          path: ./dist/**/*
