name: Multi-Platform OpenTelemetry Distribution Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Package
        uses: observiq/otel-distro-builder@v1
        with:
          manifest: collector/manifest.yaml
          output-dir: ./dist
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container images
        uses: docker/build-push-action@v5
        with:
          context: ./dist
          file: ./dist/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/collector:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/collector:latest

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collector-packages
          path: ./dist/**/*
