version: 2
project_name: __DISTRIBUTION__
env:
  - COSIGN_YES=true
builds:
  - id: __DISTRIBUTION__
    goos: __GOOS__
    goarch: __GOARCH__
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: __DISTRIBUTION__
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: __DISTRIBUTION__
    ids:
      - __DISTRIBUTION__
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - supervisor_config.yaml
      - src: _contrib/supervisor_{{ .Os }}_{{ .Arch }}{{ .ArtifactExt }}
        dst: supervisor
      - src: __DISTRIBUTION__.service
        dst: "service/__DISTRIBUTION__.service"
      - src: __DISTRIBUTION__.conf
        dst: "service/__DISTRIBUTION__.conf"
    format_overrides:
      - goos: windows
        formats: ["zip"]

  - id: __DISTRIBUTION___otelcol
    ids:
      - __DISTRIBUTION__
    name_template: "{{ .ProjectName }}_otelcol_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - collector_config.yaml
      - src: __DISTRIBUTION___otelcol.service
        dst: "service/__DISTRIBUTION__.service"
      - src: __DISTRIBUTION___otelcol.conf
        dst: "service/__DISTRIBUTION__.conf"

nfpms:
  - package_name: __DISTRIBUTION__
    file_name_template: '{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    bindir: /opt/__DISTRIBUTION__
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    id: __DISTRIBUTION__
    ids:
      - __DISTRIBUTION__
    formats:
      - apk
      - deb
      - rpm
    description: OpenTelemetry Collector with OpAMP Supervisor - __DISTRIBUTION__
    license: Apache 2.0
    contents:
      # systemd service files
      - src: __DISTRIBUTION__.service
        dst: /lib/systemd/system/__DISTRIBUTION__.service
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: __DISTRIBUTION__.conf
        dst: /etc/__DISTRIBUTION__/__DISTRIBUTION__.conf
        type: config|noreplace
        file_info:
          mode: 0644
          owner: root
          group: root

      # directory and files for the OpenTelemetry Collector distribution
      - dst: /opt/__DISTRIBUTION__
        type: dir
        file_info:
          mode: 0755
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__
      - src: _contrib/supervisor_{{.Os}}_{{.Arch}}{{ .ArtifactExt }}
        dst: /opt/__DISTRIBUTION__/supervisor{{ .ArtifactExt }}
        file_info:
          mode: 0755
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__
      - src: supervisor_config.yaml
        dst: /opt/__DISTRIBUTION__/supervisor_config.yaml
        file_info:
          mode: 0644
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__
      - dst: /opt/__DISTRIBUTION__/supervisor_storage
        type: dir
        file_info:
          mode: 0750
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__

  - package_name: __DISTRIBUTION___otelcol
    file_name_template: '{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    bindir: /opt/__DISTRIBUTION__
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    id: __DISTRIBUTION___otelcol
    ids:
      - __DISTRIBUTION__
    formats:
      - apk
      - deb
      - rpm
    description: OpenTelemetry Collector - __DISTRIBUTION__
    license: Apache 2.0
    contents:
      # systemd service files
      - src: __DISTRIBUTION___otelcol.service
        dst: /lib/systemd/system/__DISTRIBUTION__.service
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: __DISTRIBUTION___otelcol.conf
        dst: /etc/__DISTRIBUTION__/__DISTRIBUTION__.conf
        type: config|noreplace
        file_info:
          mode: 0644
          owner: root
          group: root

      # directory and files for the OpenTelemetry Collector distribution
      - dst: /opt/__DISTRIBUTION__
        type: dir
        file_info:
          mode: 0755
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__
      - src: collector_config.yaml
        dst: /opt/__DISTRIBUTION__/collector_config.yaml
        file_info:
          mode: 0644
          owner: __DISTRIBUTION__
          group: __DISTRIBUTION__

dockers:
  - id: linux-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.GITHUB_REPOSITORY_OWNER }}/__DISTRIBUTION___amd64:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/__DISTRIBUTION___amd64:latest"
    dockerfile: "Dockerfile"
    extra_files:
      - supervisor_config.yaml
      - _contrib/supervisor_{{.Os}}_{{.Arch}}{{ .ArtifactExt }}

snapshot:
  version_template: "{{ .Version }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
