version: 2
project_name: __DISTRIBUTION__
env:
  - COSIGN_YES=true
builds:
  - id: __DISTRIBUTION__
    goos: __GOOS__
    goarch: __GOARCH__
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: __DISTRIBUTION__
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: __DISTRIBUTION__
    ids:
      - __DISTRIBUTION__
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - supervisor_config.yaml
      - src: _contrib/supervisor_{{ .Os }}_{{ .Arch }}{{ .ArtifactExt }}
        dst: supervisor
      - src: __DISTRIBUTION__.service
        dst: "service/__DISTRIBUTION__.service"
      - src: __DISTRIBUTION__.conf
        dst: "service/__DISTRIBUTION__.conf"
    format_overrides:
      - goos: windows
        formats: ["zip"]

  - id: __DISTRIBUTION___otelcol
    ids:
      - __DISTRIBUTION__
    name_template: "{{ .ProjectName }}_otelcol_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - collector_config.yaml
      - src: __DISTRIBUTION___otelcol.service
        dst: "service/__DISTRIBUTION__.service"
      - src: __DISTRIBUTION___otelcol.conf
        dst: "service/__DISTRIBUTION__.conf"

# __NFPMS_CONFIG__

snapshot:
  version_template: "{{ .Version }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
