name: Base Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements-dev.txt

      - name: Check Formatting
        run: make check-format

      - name: Run Type Checks
        run: make type-check

      - name: Run Linting
        run: make lint

      - name: Check Shell Scripts
        run: make shell-check

      - name: Run Unit Tests
        run: make unit-test

  build-tests:
    name: Build Tests
    runs-on: ubuntu-latest
    needs: quality # Only run if quality checks pass
    strategy:
      matrix:
        manifest: [simple] # We'll keep just the simple build in base tests
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          # Remove unnecessary large packages
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          # Clean up docker images
          docker system prune -af
          # Clean apt cache
          sudo apt-get clean
          df -h

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          cache: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements-dev.txt

      - name: Run Build Test - ${{ matrix.manifest }}
        run: make build-test
