name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Python package
        run: |
          python -m pip install --upgrade pip build
          python -m build
          ls -la dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            LICENSE
            README.md
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
