name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      checks: write # Required for publishing test results

    steps:
      - name: Free Disk Space
        run: |
          # Remove unnecessary large packages
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          # Clean up docker images
          docker system prune -af
          # Clean apt cache
          sudo apt-get clean
          df -h

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          cache: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements-dev.txt

      - name: Run Quality Checks
        run: |
          make quality

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: builder/requirements-dev.txt

      - name: Clean build artifacts
        run: |
          rm -rf ./artifacts
          docker system prune -af
          df -h

      - name: Run Tests
        run: |
          python -m pytest builder/tests/test_build.py -v
