name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        run: |
          # Remove unnecessary large packages
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          # Clean up docker images
          docker system prune -af
          # Clean apt cache
          sudo apt-get clean
          df -h

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          make lint

      - name: Clean build artifacts
        run: |
          rm -rf ./artifacts
          docker system prune -af
          df -h

      - name: Test example manifests
        run: |
          for manifest in tests/manifests/*.yml; do
            echo "Testing manifest: $manifest"
            ./run_local_build.sh -m "$manifest" -o "./artifacts/$(basename "$manifest" .yml)"
            # Clean up after each build to save space
            docker system prune -af
          done
